<?php

namespace clientsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends EntityRepository
{
	public function findAllJoinedToPermission()
	{
		$query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT u, p FROM clientsBundle:user u
	            JOIN u.permission p'
	        );

	        return $query->getResult();
	}

	public function findOneByUsernameJoinedToPermission($id)
	{
		$query = $this->getEntityManager()
        	->createQuery(
	            'SELECT u, p FROM clientsBundle:user u
	            JOIN u.permission p
	            WHERE u.id = :id'
        	)->setParameter('id', $id);


	        return $query->getResult();
	}
}
